server:
  port: 8704

spring:
  application:
    name: eureka-service

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8701/eureka
  instance:
    hostname: localhost