server:
  port: 8705

spring:
  application:
    name: consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8701/eureka,http://localhost:8702/eureka,http://localhost:8703/eureka
  instance:
    hostname: localhost
